home_kolomiets_homepage:
    path:     /
    defaults: { _controller: HomeKolomietsBundle:Parameter:withoutParam }

home_kolomiets_withoutParam:
    path:     /without_param
    defaults: { _controller: HomeKolomietsBundle:Parameter:withoutParam }

home_kolomiets_oneParam:
    path:     /with_one_param/{slug}
    defaults: { _controller: HomeKolomietsBundle:Parameter:oneParam, slug: 'DEFAULT' }

home_kolomiets_twoParam:
    path:     /with_two_param/{one}/{two}
    defaults: { _controller: HomeKolomietsBundle:Parameter:twoParam }

home_kolomiets_requirementDigitalParam:
    path:     /with_requirement/{slug}
    defaults: { _controller: HomeKolomietsBundle:Parameter:requirementDigitalParam }
    requirements:
        slug: '\d+'

home_kolomiets_requirementStringParam:
    path:     /with_requirement/{slug}
    defaults: { _controller: HomeKolomietsBundle:Parameter:requirementStringParam }
    requirements:
        slug: '\D+'