home_kolomiets:
    resource: "@HomeKolomietsBundle/Resources/config/routing.yml"
    prefix:   /

admin_kolomiets:
    resource: "@HomeKolomietsBundle/Resources/config/admin_routing.yml"
    prefix: /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
